
"""
This file stores the training examples used by the intent classifier.
The examples help the chatbot learn how to recognize different types
of astrology questions.
"""

TRAINING_SAMPLES = [
    # Traits
    ("Aries traits", "traits"),
    ("Taurus traits", "traits"),
    ("Gemini traits", "traits"),
    ("Cancer traits", "traits"),
    ("Leo traits", "traits"),
    ("Virgo traits", "traits"),
    ("Libra traits", "traits"),
    ("Scorpio traits", "traits"),
    ("Sagittarius traits", "traits"),
    ("Capricorn traits", "traits"),
    ("Aquarius traits", "traits"),
    ("Pisces traits", "traits"),
    ("Tell me about Aries", "traits"),
    ("Tell me about Cancer", "traits"),
    ("Tell me about Leo", "traits"),
    ("What is Virgo like?", "traits"),
    ("What is Scorpio like?", "traits"),
    ("Describe Pisces personality", "traits"),
    ("Describe Gemini personality", "traits"),
    ("What are the personality traits of Taurus?", "traits"),
    ("What kind of person is Capricorn?", "traits"),
    ("Tell me about Aquarius energy", "traits"),

    # Compatibility
    ("Aries compatibility", "compatibility"),
    ("Taurus compatibility", "compatibility"),
    ("Gemini compatibility", "compatibility"),
    ("Cancer compatibility", "compatibility"),
    ("Leo compatibility", "compatibility"),
    ("Virgo compatibility", "compatibility"),
    ("Libra compatibility", "compatibility"),
    ("Scorpio compatibility", "compatibility"),
    ("Sagittarius compatibility", "compatibility"),
    ("Capricorn compatibility", "compatibility"),
    ("Aquarius compatibility", "compatibility"),
    ("Pisces compatibility", "compatibility"),
    ("Who is Aries compatible with?", "compatibility"),
    ("Who is Cancer compatible with?", "compatibility"),
    ("Who is Leo compatible with?", "compatibility"),
    ("What signs match with Virgo?", "compatibility"),
    ("What signs match with Pisces?", "compatibility"),
    ("Is Cancer compatible with Sagittarius?", "compatibility"),
    ("Are Taurus and Virgo compatible?", "compatibility"),
    ("Can Scorpio and Pisces work together?", "compatibility"),
    ("Who should Libra date?", "compatibility"),
    ("What is the best match for Capricorn?", "compatibility"),

    # Ruling planet
    ("Aries ruling planet", "ruling_planet"),
    ("Taurus ruling planet", "ruling_planet"),
    ("Gemini ruling planet", "ruling_planet"),
    ("Cancer ruling planet", "ruling_planet"),
    ("Leo ruling planet", "ruling_planet"),
    ("Virgo ruling planet", "ruling_planet"),
    ("Libra ruling planet", "ruling_planet"),
    ("Scorpio ruling planet", "ruling_planet"),
    ("Sagittarius ruling planet", "ruling_planet"),
    ("Capricorn ruling planet", "ruling_planet"),
    ("Aquarius ruling planet", "ruling_planet"),
    ("Pisces ruling planet", "ruling_planet"),
    ("What planet rules Aries?", "ruling_planet"),
    ("What planet rules Cancer?", "ruling_planet"),
    ("What planet rules Pisces?", "ruling_planet"),
    ("Who rules Leo?", "ruling_planet"),
    ("Which planet governs Scorpio?", "ruling_planet"),
    ("What is Virgo's ruling planet?", "ruling_planet"),
    ("Tell me the ruling planet of Libra", "ruling_planet"),

    # Element
    ("Aries element", "element"),
    ("Taurus element", "element"),
    ("Gemini element", "element"),
    ("Cancer element", "element"),
    ("Leo element", "element"),
    ("Virgo element", "element"),
    ("Libra element", "element"),
    ("Scorpio element", "element"),
    ("Sagittarius element", "element"),
    ("Capricorn element", "element"),
    ("Aquarius element", "element"),
    ("Pisces element", "element"),
    ("What element is Aries?", "element"),
    ("What element is Cancer?", "element"),
    ("What element is Pisces?", "element"),
    ("Is Virgo an earth sign?", "element"),
    ("Is Gemini an air sign?", "element"),
    ("Tell me Leo's element", "element"),
    ("Which zodiac element belongs to Scorpio?", "element")
]